export const USER_STAT = {
  STAT_ATTACK: "스텟 공격력",
  ATTACK: "공격력",
  MAX_ATTACK: "최대 스탯공격력",
  DAMAGE: "데미지",
  BOSS_ATTACK: "보스 몬스터 데미지",
  FINAL_DAMAGE: "최종 데미지",
  BANG_MU: "방어율 무시",
  NORMAL_DAMAGE: "일반 몬스터 데미지",
  HORSEPOWER: "마력",
  CRITICAL_CHANCE: "크리티컬 확률",
  CRITICAL_DAMAGE: "크리티컬 데미지",
  COLLDOWN: "재사용 대기시간 감소 (초)",
  COLLDOWN_PERCENT: "재사용 대기시간 감소 (%)",
  BUFF_DURATION: "버프 지속시간",
  NOT_COLLDOWN: "재사용 대기시간 미적용",
  IGNORE_RESISTANCE: "속성 내성 무시",
  ADDITIONAL_DAMAGE: "상태이상 추가 데미지",
  INCREASED_DURATION: "소환수 지속시간 증가",
  HP: "HP",
  MP: "MP",
  STR: "STR",
  DEX: "DEX",
  INT: "INT",
  LUK: "LUK",
  ITEM_DROP: "아이템 드롭률",
  MESO_DROP: "메소 획득량",
  ATTACK_SPEED: "공격 속도",
  EXP: "추가 경험치 획득",
  WEAPONE: "무기 숙련도",
  STAR_FORCE: "스타포스",
  ARCANDE_FORCE: "아케인포스",
  AUTHENTIC_FORCE: "어센틱포스",
  STANS: "스탠스",
  DEFENSE: "방어력",
  JUMPING_POWER: "점프력",
  TOLERANCE: "상태이상 내성",
  SPEED: "이동속도",
};
