export const USER_STAT = {
  ATTACK: "공격력",
  MAX_ATTACK: "최대 스탯공격력",
  DAMAGE: "데미지",
  BOSS_ATTACK: "보스 몬스터 데미지",
  FINAL_DAMAGE: "최종 데미지",
  BANG_MU: "방어율 무시",
  NORMAL_DAMAGE: "일반 몬스터 데미지",
  HORSEPOWER: "마력",
  CRITICAL_CHANCE: "크리티컬 확률",
  CRITICAL_DAMAGE: "크리티컬 데미지",
  COLLDOWN: "재사용 대기시간 감소 (초)",
  COLLDOWN_PERCENT: "재사용 대기시간 감소 (%)",
  BUFF_DURATION: "버프 지속시간",
  NOT_COLLDOWN: "재사용 대기시간 미적용",
  IGNORE_RESISTANCE: "속성 내성 무시",
  ADDITIONAL_DAMAGE: "상태이상 추가 데미지",
  INCREASED_DURATION: "소환수 지속시간 증가",
};
